### ISSUE TITLE
AxiDraw not respecting "Plot individual layers" options

### ISSUE THREAD

**Issue by haschdl** [evil-mad/axidraw#146] opened 2023-02-25 13:37 UTC
AxiDraw is plotting all layers, regardless of the selection in Layers tab.  

My SVG file consists of 3 layers, named "1 Hatching", "2 Stroke" and "Guide 30x40".  Using the Layers tab, and picking "1" for the layer option, the plotter will do layer 1, then proceed to plot also the elements inside the "Guide" layer.   The behaviour is consistent also using the Preview mode.
 
![image](https://user-images.githubusercontent.com/9550197/221359686-25cb56ae-3769-4ff6-9b1d-f89b69faf894.png)

This is probably something with my SVG, however I couldn't figure out on my own. 

https://user-images.githubusercontent.com/9550197/221359806-1b8df30c-0d08-4505-87ed-577e0b331392.svg

**Comment by oskay** [comment] 2023-02-25 18:09
I am able to reproduce this, and at first glance, it looks like a genuine bug. I'll look into this further.

As a short-term workaround, consider adding a "%" to the beginning of the names of layers that you don't want to print.

**Comment by haschdl** [comment] 2023-02-26 19:14
> As a short-term workaround, consider adding a "%" to the beginning of the names of layers that you don't want to print.

Thank you @oskay, I'll be monitoring the issue for an update.

**Comment by oskay** [comment] 2023-02-26 21:23
Should be fixed in version 3.8.1, released today.

**Closed as completed by oskay** 2023-02-26 21:23 UTC
Labels: bug, Completed
