### ISSUE TITLE
Facing error when axidraw is writing 

### ISSUE THREAD

**Issue by basicspace26** [evil-mad/axidraw#30] opened 2017-03-09 15:34 UTC
Started the program and after a few words, 

"Traceback (most recent call last):

  File "axidraw.py", line 2047, in <module>

    e.affect()

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 268, in affect

    self.effect()

  File "axidraw.py", line 253, in effect

    self.plotDocument()

  File "axidraw.py", line 519, in plotDocument

    self.recursivelyTraverseSvg( self.svg, self.svgTransform )

  File "axidraw.py", line 584, in recursivelyTraverseSvg

    self.recursivelyTraverseSvg( node, matNew, parent_visibility=v )			

  File "axidraw.py", line 584, in recursivelyTraverseSvg

    self.recursivelyTraverseSvg( node, matNew, parent_visibility=v )			

  File "axidraw.py", line 584, in recursivelyTraverseSvg

    self.recursivelyTraverseSvg( node, matNew, parent_visibility=v )			

  File "axidraw.py", line 641, in recursivelyTraverseSvg

    self.plotPath( node, matNew )

  File "axidraw.py", line 1012, in plotPath

    if len( simplepath.parsePath( d ) ) == 0:

  File "C:\Program Files (x86)\Inkscape\share\extensions\simplepath.py", line 110, in parsePath

    raise Exception, 'Invalid path, no initial command.'    

Exception: Invalid path, no initial command."

The program gets stuck there and Axidraw is unable to work.

**Comment by oskay** [comment] 2017-03-09 17:30
The program is saying that you have an invalid path. It is halting there intentionally, and giving you an error message. 

The code says that there is an error in your path. That alone does not necessarily indicate that there is a problem with the code. 

Is there a chance that it is correct-- do you have an invalid path there?

**Comment by basicspace26** [comment] 2017-03-10 02:42
I've check every single letter/ path but I don't see any error on it. It only happens when the axidraw is writing it. Funnily, it doesn't work when there are a lot of words ? Not sure what's causing it.

**Comment by oskay** [comment] 2017-03-10 02:46
Perhaps you could attach a file that reproduces this issue here-- (if you zip it first, that's an allowed attachment type). 

How was the file created?

**Comment by basicspace26** [comment] 2017-03-10 02:50
It was created on inkscape followed by using the render tool - hersey text, followed by arranging the words in an orderly manner. Unable to get the file at the moment, it's on the home computer.

**Comment by oskay** [comment] 2017-03-10 02:54
Possible workaround, in the mean time, if it is an invalid path that you've got there.

Edit > Select all in all layers
Object > Ungroup (possibly more than once, if you have things multiply grouped)
Path > Object to path

**Comment by oskay** [comment] 2017-03-10 02:57
I'm the author of Hershey Text as well, so if there error is over there, we should be able to fix it as well. Would definitely need to see the file (or one that reproduces it) to go further.

It would be helpful to know what font, and what character(s) caused this issue. It's possible that there is a malformed character in one of the fonts, which is causing the problem.

**Comment by basicspace26** [comment] 2017-03-10 03:01
Great, I'll try it out later.  I'll send the file over later. Great job by the way 👍

**Comment by oskay** [comment] 2017-03-10 03:02
Oops. Wrong button.

**Comment by su-v** [comment] 2017-03-10 04:30
A similar issue had been filed for Inkscape (also exposed by paths generated with the Hershey Text extension, apparently triggered by <kbd>space</kbd> characters in the original text):
* Bug #1646595 [cubicsuperpath crashes on some paths](https://bugs.launchpad.net/inkscape/+bug/1646595)

The reporter there also provided a proposed patch for the Hershey Text extension (the one bundled with Inkscape). Code review is still pending, though likely a solution to improve the functions in Inkscape's `simplepath.py` (and/or `cubicsuperpath.py`) would be preferred (instead of patching individual extensions that might generate paths which are not well-formed).

**Comment by oskay** [comment] 2017-03-10 08:14
@su-v Interesting, I had not seen that. The more recent versions of Hershey Text (still hosted in the https://github.com/evil-mad/EggBot repository) have a separate fix for the space issue:
At line 79, change:
`                if (q < 0) or (q > 95):` to
`                if (q <= 0) or (q > 95):`.

However, I agree that the proposed fix from there is also appropriate, since it handles the general case, should there be another mis-formed character in the font. I have caught and corrected other character errors like this (due to errors in the fonts themselves), but catching the general cases is a much better approach.

**Comment by oskay** [comment] 2017-03-10 10:19
I'm attaching an updated version of hershey.py, the primary script of Hershey Text for you to try. It contains the patch referred to by su-v, which should catch certain classes of font description errors.  Please let me know if this fixes the issue for you.

Unzip the file and copy it to your Inkscape Extensions directory, replacing the copy there. Your extensions directory is most likely located at: `C:\Program Files\Inkscape\share\extensions\`

[hershey.zip](https://github.com/evil-mad/axidraw/files/833587/hershey.zip)

**Comment by muaathtaleb** [comment] 2017-04-24 09:06
hi
I want to know what the printing order is for a machine to work Axidraw .

**Comment by oskay** [comment] 2017-04-24 09:11
@muaathtaleb 
This does not sound related to this issue. If you are having an issue with printing order, please open a separate issue for that.

Edit: I have deleted one more unrelated message from @muaathtaleb in this issue.  @muaathtaleb: If you have an issue that is unrelated to this, please either open a new issue for it or contact technical support directly.

**Comment by muaathtaleb** [comment] 2017-04-24 10:18
Warning: unable to hatch object <{http://www.w3.org/2000/svg}image>, please convert it to a path first.

 Nothing to plot

**Comment by oskay** [comment] 2017-06-07 18:21
Closing this issue until we have a demonstration file that shows the issue still present.

**Closed as completed by oskay** 2017-06-07 18:21 UTC
Labels: need-info
