### ISSUE TITLE
axidraw inkscape plugin not working in macOS BigSur

### ISSUE THREAD

**Issue by dcoeurjo** [evil-mad/axidraw#85] opened 2020-08-22 18:32 UTC
When using the Inkscape plugin on macOS BigSur (beta at this point but should be released pretty soon), there is a `pyserial` issue when trying to communicate with the axidraw):

```
Traceback (most recent call last):
  File "axidraw_control.py", line 250, in <module>
    exit_status.run(e.affect)
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/ink_extensions_utils/exit_status.py", line 26, in run
    return func(*args, **kwargs)
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/ink_extensions/inkex.py", line 285, in affect
    self.effect()
  File "axidraw_control.py", line 171, in effect
    self.plot_to_axidraw(self.options.port, True)
  File "axidraw_control.py", line 232, in plot_to_axidraw
    ad.effect()
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw.py", line 346, in effect
    self.serial_connect()
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw.py", line 2812, in serial_connect
    self.serial_port = ebb_serial.openPort()
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/plotink/ebb_serial.py", line 305, in openPort
    found_port = findPort()
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/plotink/ebb_serial.py", line 53, in findPort
    from serial.tools.list_ports import comports
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/davidcoeurjolly/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/axidraw_deps/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
```
The `pyserial` related issue is this one: https://github.com/pyserial/pyserial/issues/509 
Once fixed from in the `pyserial` upstream that would probably mean a new release of the axidraw plugin.

**Comment by oskay** [comment] 2020-08-22 18:40
Which version of the AxiDraw plugin?

Last I tested (on a previous Big Sur beta), Inkscape was not working correctly on Big Sur-- I'm glad to hear that it is working now.

And, last I tested on Big Sur, the AxiDraw CLI was working properly -- suggesting that the serial library was working. I have also been watching that pyserial issue.

I'll update to the newest Big Sur and see what the situation is.

**Comment by dcoeurjo** [comment] 2020-08-22 19:02
oops I should have mentioned this: Inkscape 1.0 (4035a4f, 2020-05-01), AxiDraw control 2.5.7 

No problem with Inkscape but the usb connexion to the axidraw is not working :/

**Comment by dcoeurjo** [comment] 2020-08-22 19:03
(Big Sur beta 11.0 (20A5354i))

**Comment by dcoeurjo** [comment] 2020-08-22 19:05
I should try the axidraw CLI but I'm not very familiar with that one.

**Comment by oskay** [comment] 2020-08-22 19:21
It looks like the underlying issues are being addressed actively and aggressively by developers including some from Python and Apple:

https://bugs.python.org/issue41179
https://bugs.python.org/issue41100

From what I can see, it looks like we should expect the underlying behavior to continue to change in the immediate future.

We should definitely keep an eye on the issue and monitor the progress. But for the moment, I don't think that there is anything that we necessarily can or should try to do about it.

**Comment by dcoeurjo** [comment] 2020-08-23 17:07
Thanks for the quick feedback. 
FYI: I've just tried the `axicli` (2.6.3) and I have the same issue.

**Comment by oskay** [comment] 2020-08-23 19:30
That seems consistent and expected for the present status. The CLI and Inkscape software are wrappers around the same software core.

**Comment by oskay** [comment] 2020-08-26 00:48
Confirmed on current Big Sur beta.

**Comment by oskay** [comment] 2020-09-14 21:38
Possible approach: https://github.com/pyserial/pyserial/pull/518

**Comment by alessbell** [comment] 2020-11-13 15:42
Looks like a PR was just opened to address this: https://github.com/pyserial/pyserial/pull/542

**Comment by oskay** [comment] 2020-11-13 17:01
@dcoeurjo @alessbell We *believe* that the issue is resolved in AxiDraw software version 2.7.0, and were about to pull the changes into the repository and close the issue.   Would you be willing to try it out and see?   http://axidraw.com/sw

**Comment by dcoeurjo** [comment] 2020-11-13 17:25
@oskay Thanks for the update, the 2.7.0 works perfectly on my BigSur 
🎉

**Comment by oskay** [comment] 2020-11-13 17:36
Great; thanks!

**Closed as completed** 2020-11-13 17:43 UTC
Labels: Mac
