### ISSUE TITLE
Hatch fill issues

### ISSUE THREAD

**Issue by LuisDiazUgena** [evil-mad/axidraw#13] opened 2016-09-01 16:49 UTC
Hi!

Just recieved my AxiDraw today and it's awesome (works like a charm), but I'm having some issues related with Hatch Fill inkscape extension.

I've a svg file that have a text path, but when trying to do the fill part, it says two errors:
1. Unable to drwaw object http://www.w3.org/2000/svg}wcb>
2. The other one it's: 
   `Traceback (most recent call last):
   File "eggbot_hatch.py", line 1719, in <module>
     e.affect()
   File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 265, in affect
     self.getposinlayer()
   File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 207, in getposinlayer
     x = self.unittouu( xattr[0] + 'px' )
   File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 351, in unittouu
     return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
   File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 304, in getDocumentUnit
     p = param.match(svgwidth)
   TypeError: expected string or buffer
   `

¡Hope to get this working soon!

Thanks so much!

**Comment by oskay** [comment] 2016-09-01 21:12
1. Convert your object to a path before trying to draw or fill it. If you continue to have difficulty after converting it to a path, please state specifically what object type it is, and steps to reproduce the issue.
2. Duplicate of #5. Please set your document units to inches or centimeters before attempting to fill or plot-- for example by using the A4 or Letter document template in Inkscape.

**Closed as completed by oskay** 2016-09-01 21:12 UTC
