### ISSUE TITLE
Bug Report: Bézier Curve not drawing smoothly

### ISSUE THREAD

**Issue by simlu** [evil-mad/axidraw#41] opened 2017-08-19 17:56 UTC
There seems to be an issue where a simple Bézier curve is not drawn "smoothly" - meaning the speed fluctuates while drawing the line, resulting in a drawing that has some parts of the line thinner than others.

Here is a 

> [Video of the Problem](https://drive.google.com/open?id=0B46auzFhNrCbN0FZblMxYzBfZkgxYm9YMm1UMDJpNHo0d3lR) (listen to the sound)

and here is the corresponding

> [Svg File](https://github.com/evil-mad/axidraw/files/1236543/testLineNotSmooth.zip) (containing just one Bézier Curve)

Using Windows 7, inkscape 0.91, axidraw extension 1.5.9 and ebb firmware 2.5.1.

When running the sample file the problem is very noticeable. I haven't done any explicit testing with older versions, but I'm confident that the issue wasn't present in release 1.2.2.

I tried my best to include all the relevant information in this report. Please let me know if you require anything else.

**Comment by oskay** [comment] 2017-08-19 20:22
Confirmed, and confirmed that it was not present in 1.2.2.

Not present in constant-speed mode.  Appears to be due to slowing down at corners being "over-interpreted" to include straight (no bend) vertices.

**Comment by oskay** [comment] 2017-10-17 08:28
This turns out to have been a "simple" matter of unit conversion, but pointed to a deeper problem in how the units were handled, which allowed that type of error to occur in the first place. This issue, along with the underlying set of issues, is fixed in a developmental version that will be released soon.

**Comment by simlu** [comment] 2017-10-18 04:01
Sweet! Looking forward to testing it out!

**Closed as completed** 2017-10-21 02:11 UTC
Labels: bug
