### ISSUE TITLE
Unable to fresh install via pip

### ISSUE THREAD

**Issue by alexbainter** [evil-mad/axidraw#94] opened 2020-11-28 21:14 UTC
Hello, I'm trying to do a fresh install of the Python API following the instructions [here](https://axidraw.com/doc/py_api/#installation) but I'm getting the following error:

```bash
    Cannot uninstall requirement axidrawinternal, not installed
    Traceback (most recent call last):
      File "/tmp/pip-mzz0koy9-build/setup.py", line 43, in replacement_setup
        [sys.executable, '-m', 'pip', 'uninstall', '--yes', pkg_name])
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'uninstall', '--yes', 'axidrawinternal']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-mzz0koy9-build/setup.py", line 74, in <module>
        'htacli = axicli.__main__:hta_CLI',
      File "/tmp/pip-mzz0koy9-build/setup.py", line 46, in replacement_setup
        raise RuntimeError("Could not install one or more prebuilt dependencies.") from err
    RuntimeError: Could not install one or more prebuilt dependencies.
```

Seems to have been introduced [here](https://github.com/evil-mad/axidraw/pull/93/files#diff-ec5d2c5f6329375538e730b11d4c310e617eb6247a77103ed79ffe1ec3336097R42) but I don't speak Python :sweat_smile: .

Thank you for making these wonderful tools!

**Comment by alexbainter** [comment] 2020-11-28 21:29
Managed to get it installed with this workaround:

# Workaround
1. Download [AxiDraw_API.zip from the previous version (v2.6.3)](https://github.com/evil-mad/axidraw/releases/download/2.6.3/AxiDraw_Mac_263.zip).
2. Extract the archive, `cd` to the directory, and run `pip install .` (or in my case, `pip3 install .`). Now v2.6.3 is available.
3. To upgrade to latest version, follow the normal instructions [here](https://axidraw.com/doc/py_api/#installation).

**Comment by oskay** [comment] 2020-11-28 21:36
Can you give some information about your OS?

**Comment by alexbainter** [comment] 2020-11-28 21:46
:facepalm: My b, I'm on Elementary OS 5.1 (Ubuntu 18.04 based).

My default `python` executable seems to be Python 2.7.17 but I also have Python 3.6.9 installed. I tried
`python -m pip install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip`
and 
`pip install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip`
and
`pip3 install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip`
and got the same error from each.

**Comment by oskay** [comment] 2020-11-28 22:58
Confirmed.

**Comment by oskay** [comment] 2020-12-22 20:14
Should be fixed now.

**Closed as completed by oskay** 2020-12-22 20:14 UTC
Labels: bug, Linux

**Comment by x37v** [comment] 2021-01-16 23:30
I'm experiencing the same issue, 
```shell
python --version
Python 3.6.9
alex@shred:~/local/src/axidraw/inkscape driver$  python -m pip install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
Collecting https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
  Using cached https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip
    Complete output from command python setup.py egg_info:
    Cannot uninstall requirement axidrawinternal, not installed
    Traceback (most recent call last):
      File "/tmp/pip-1osqpl4h-build/setup.py", line 43, in replacement_setup
        [sys.executable, '-m', 'pip', 'uninstall', '--yes', pkg_name])
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'uninstall', '--yes', 'axidrawinternal']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-1osqpl4h-build/setup.py", line 76, in <module>
        'htacli = axicli.__main__:hta_CLI',
      File "/tmp/pip-1osqpl4h-build/setup.py", line 44, in replacement_setup
        except CalledProcessError: # Will be raised if there is no version to uninstall
    NameError: name 'CalledProcessError' is not defined
    WARNING: It looks like you might be attempting to install this in a non-pip way. This is discouraged. Use `pip install .` (or `pip install -r requirements.txt` if you are a developer with access to the relevant private repositories).
```

**Comment by oskay** [comment] 2021-01-16 23:33
Can you try using a fresh copy?

**Comment by x37v** [comment] 2021-01-17 01:07
> Can you try using a fresh copy?

I'm not sure what you mean.

**Comment by oskay** [comment] 2021-01-17 01:07
> Using cached https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip

**Comment by x37v** [comment] 2021-01-17 01:14
that zip contains `axicli-2.7.0r11/`
Is that expected? The release zip on the github page contains `ad_api_263_r1`

**Comment by oskay** [comment] 2021-01-17 01:18
Yes, that's what I get as well.

**Comment by x37v** [comment] 2021-01-17 01:25
```shell
cd ../axicli-2.7.0r11/
alex@shred:~/local/src/axidraw/axicli-2.7.0r11$ pip3 install .
Processing /home/alex/local/src/axidraw/axicli-2.7.0r11
    Complete output from command python setup.py egg_info:
    Cannot uninstall requirement axidrawinternal, not installed
    Traceback (most recent call last):
      File "/tmp/pip-pvn119o3-build/setup.py", line 43, in replacement_setup
        [sys.executable, '-m', 'pip', 'uninstall', '--yes', pkg_name])
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'uninstall', '--yes', 'axidrawinternal']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-pvn119o3-build/setup.py", line 76, in <module>
        'htacli = axicli.__main__:hta_CLI',
      File "/tmp/pip-pvn119o3-build/setup.py", line 44, in replacement_setup
        except CalledProcessError: # Will be raised if there is no version to uninstall
    NameError: name 'CalledProcessError' is not defined
    WARNING: It looks like you might be attempting to install this in a non-pip way. This is discouraged. Use `pip install .` (or `pip install -r requirements.txt` if you are a developer with access to the relevant private repositories).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-pvn119o3-build/
```

**Comment by oskay** [comment] 2021-01-17 01:46
I'm not able to reproduce this, but there's a second `NameError` that I can fix; please try the attached, and see if this gives a different error. 
[axicli-2.7.0r12.zip](https://github.com/evil-mad/axidraw/files/5825410/axicli-2.7.0r12.zip)

**Comment by x37v** [comment] 2021-01-17 01:52
success!
```
alex@shred:~/local/src/axidraw/axicli-2.7.0r12$ pip3 install .
Processing /home/alex/local/src/axidraw/axicli-2.7.0r12
Collecting ink_extensions>=1.1.0 (from pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/06/64/a7446c9e9856d6868b37fbd6bdb21758107c4caf35d60c918a8fcc80c22a/ink_extensions-1.1.0-py3-none-any.whl
Collecting lxml (from pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/bd/78/56a7c88a57d0d14945472535d0df9fb4bbad7d34ede658ec7961635c790e/lxml-4.6.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting plotink>=1.2.2 (from pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/fe/9f/f6cc2603a1a67ffef84d9dd0571204a54a8493502eb13d6880cbda825f04/plotink-1.2.2-py3-none-any.whl
Collecting requests (from pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl
Collecting pyserial>=3.5 (from plotink>=1.2.2->pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
Collecting chardet<5,>=3.0.2 (from requests->pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests->pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->pyaxidraw==2.7.0)
  Using cached https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl
Building wheels for collected packages: pyaxidraw
  Running setup.py bdist_wheel for pyaxidraw ... done
  Stored in directory: /home/alex/.cache/pip/wheels/7e/ea/48/7dcafcf8b0c376ab64cc82b30b74dc7f6f6e32ae774829b16c
Successfully built pyaxidraw
Installing collected packages: lxml, ink-extensions, pyserial, plotink, chardet, idna, urllib3, certifi, requests, pyaxidraw
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 ink-extensions-1.1.0 lxml-4.6.2 plotink-1.2.2 pyaxidraw-2.7.0 pyserial-3.5 requests-2.25.1 urllib3-1.26.2
```

**Comment by soupman99** [comment] 2021-02-20 16:44
I'm also trying to get things installed and running into a similar error on macOS 11.2.1

   ```
 ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-QLJDI3/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-QLJDI3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-pip-egg-info-ryofaf
         cwd: /private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-QLJDI3/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b7/24fr3pvx1x52j2cwckznphth0000gn/T/pip-req-build-QLJDI3/setup.py", line 48
        raise RuntimeError("Could not install one or more prebuilt dependencies.") from err
                                                                                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm a nodeJS guy so I'm new to python.  Any idea what I'm doing wrong?

**Comment by oskay** [comment] 2021-02-20 19:29
> Any idea what I'm doing wrong? 

Absolutely no idea.

If this is a bug report, please open a new issue with sufficient information to reproduce the issue. That includes your OS, python version, what exact command you used, and what the result was. 

If this is a request for tech support, please use the EMS discord ( https://discord.gg/axhTzmr ) or contact form ( https://shop.evilmadscientist.com/contact ) to request support.
