### ISSUE TITLE
Hidden line removal feature vs SVG style

### ISSUE THREAD

**Issue by axel-tanner** [evil-mad/axidraw#154] opened 2023-06-02 11:57 UTC
Thank you for this very cool new feature!
When creating SVGs programmatically (in my case with https://openrndr.org/), a different format for the stroke/fill is used, eg a path looks like this

`path stroke="#000000" fill="#00ff00" d="M 100.0 100.0L300.0 100.0L300.0 300.0L100.0 300.0L100.0 100.0z"/>
`

Seemingly this is not recognized for the hidden line removal, only after changing it to this format

`<path style="fill:#00ff00;stroke:#000000" d="M 100.0 100.0L300.0 100.0L300.0 300.0L100.0 300.0L100.0 100.0z"/>
`

it nicely takes it into accound.

As to my understanding both forms are allowed in SVG files – could the software possibly also support this syntax?

… but I am very thankful for this feature overall – it makes SVG generation much easier!

**Comment by oskay** [comment] 2023-06-02 15:57
Have you tested under version 3.9.1? I believe that this particular issue may be already resolved.

**Comment by oskay** [comment] 2023-06-13 17:47
Testing with the example that you did provide, I believe that the issue is already resolved (though the path needs an opening `<`).  

I'm closing this issue with the presumption that it's resolved. If not, please feel free to comment or re-open the issue.

**Closed as completed by oskay** 2023-06-13 17:47 UTC
Labels: bug, need-info
